name: tests

on:
  workflow_dispatch: {} # allow manual triggers
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  laravel:
    name: Laravel (PHP ${{ matrix.php-version }}, SurrealDB ${{ matrix.surreal-version }})
    env:
      SURREALDB_HOST: localhost
      SURREALDB_PORT: 8000
      SURREALDB_USERNAME: root
      SURREALDB_PASSWORD: root
      SURREALDB_DATABASE: test
      SURREALDB_NAMESPACE: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: [ '8.2', '8.3', '8.4' ]
        surreal-version: [ 'v1' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, dom, fileinfo, pgsql
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-progress --optimize-autoloader

      - name: Start SurrealDB
        run: sh ./tests/scripts/docker-restart.sh ${{ matrix.surreal-version }}

      - name: Execute tests
        run: vendor/bin/pest

      - name: Stop SurrealDB
        run: sh ./tests/scripts/docker-stop.sh
